### ISSUE TITLE
XSS Injection

### ISSUE THREAD

**Issue by HexOverflow** [OctoNezd/NTRDB#10]
http://octonezd.pw/index

you can inject html/javascript code easily please fix this

**Comment by martinmontane** [comment]
OMG!!! i knew someone was going to do this.

**Comment by martinmontane** [comment]
any ways this page is awesome with just a little bet more programming it will be one of the most useful pages on the scene please continue with this.

**Comment by HexOverflow** [comment]
@OctoNezd Someone deleted the whole site via XSS.

**Comment by OctoNezd** [comment]
I dont thnik they deleted site fully, only added some malicous items, which I can safely delete

**Comment by OctoNezd** [comment]
Someone should test if XSS injection works with https://github.com/OctoNezd/NTRDB/commit/c89a99e6693600d286f5f07a2fb4d01c6bfee71b

**Comment by OctoNezd** [comment]
![image](https://cloud.githubusercontent.com/assets/15308404/23054610/09dbbd74-f4f2-11e6-8a78-b7aeab93cead.png)
Looks like I fixed bug with https://github.com/OctoNezd/NTRDB/commit/c89a99e6693600d286f5f07a2fb4d01c6bfee71b, but please test too

**Comment by OctoNezd** [comment]
Looks fixed now. Let it run for the rest of the day and look if everything is fine.
