### ISSUE TITLE
cant activate my account 

### ISSUE THREAD

**Issue by martinmontane** [OctoNezd/NTRDB#14]
the email never reached so probably will be necessary a resend activation

**Comment by martinmontane** [comment]
it stops in the while 1: to send the mail

**Comment by OctoNezd** [comment]
Do you put settings in the mailsettings.py file?

**Comment by martinmontane** [comment]
i meant in your server

**Comment by martinmontane** [comment]
yes i have it working in mine

**Comment by OctoNezd** [comment]
Everything is fine on mine side...
![image](https://cloud.githubusercontent.com/assets/15308404/23100224/9a6883fe-f68c-11e6-9cb9-6a291066db75.png)
