### ISSUE TITLE
Return sqlite support

### ISSUE THREAD

**Issue by OctoNezd** [OctoNezd/NTRDB#19]
Looks like sqlite supported screwed pretty much things, I reverted to commit w/o it.

**Comment by martinmontane** [comment]
tell me what broke so i can fix them

**Comment by martinmontane** [comment]
literally just check every thing in my version so its working. If its about the remove button then I can fix it.

**Comment by OctoNezd** [comment]
@martinmontane After user registration, site freezes

**Comment by martinmontane** [comment]
that is what happening to me right now and when the web page used pickles. the while 1 is failing again and again, sometimes work and sometimes it doesn't. I'm looking into it right now

**Comment by martinmontane** [comment]
you deleted the activation? just try to register.

**Comment by martinmontane** [comment]
identified the problem. Fixing it. will commit soon

**Comment by OctoNezd** [comment]
> you deleted the activation? just tried to register.

Yes, there were several problems with Yandex Mail. I need to switch to something other...

**Comment by martinmontane** [comment]
fixed it. You cant have a connection to the server for too long so now it connects whenever it needs to send the mail. takes a little longer but works great
any ways fixed the remove button.

**Comment by OctoNezd** [comment]
I thinked quite a bit.

I need comparison of pickle + dictionary and sqlite3. Can you give me execution time of both?

You can measure it with time.

**Comment by martinmontane** [comment]
i made a fix for everything. i'll get on the sqlite and pickle execution. the difference is mainly in the large amount of data. But trust me that you want to have database rather than a pickle file.

**Comment by OctoNezd** [comment]
I think you should make converter between both. Because I dont want to annoy people who already used pickle version.

**Comment by martinmontane** [comment]
can i have the pickles database? so i can make the converter.

**Comment by OctoNezd** [comment]
@martinmontane just make one

**Comment by martinmontane** [comment]
can you tell me the fields in the pickle database so i can make it more specific.

**Comment by martinmontane** [comment]
I think this issue is good to go
