### ISSUE TITLE
Submit NTR Plugin doesn't work somehow.

### ISSUE THREAD

**Issue by JixunMoe** [OctoNezd/NTRDB#2]
![image](https://cloud.githubusercontent.com/assets/5713045/22990169/37c22d10-f3b0-11e6-9192-b96642a620e0.png)

Chrome 56.0

**Comment by OctoNezd** [comment]
Can you provide URL?

**Comment by JixunMoe** [comment]
After click submit, this is the url shown in browser:

```
https://<my host>/?plg=111&titid=222&name=333&rid=
```

**Comment by OctoNezd** [comment]
Hmm. That really strange, for some reason it also passed rid

**Comment by JixunMoe** [comment]
Maybe add a `<form>` to the remove section will help?

**Comment by OctoNezd** [comment]
Can reproduce

**Comment by OctoNezd** [comment]
> Maybe add a <form> to the remove section will help?
Wait, there is none there?!

**Comment by JixunMoe** [comment]
![image](https://cloud.githubusercontent.com/assets/5713045/22990427/0f5a050e-f3b1-11e6-8760-d6c6d80c2d5a.png)

Not for the remove form.

**Comment by OctoNezd** [comment]
```<form method="get">
<p>Enter a Removal ID: <input type="text" name="rid" autocomplete="off"></p>
<input type="submit" value="Remove your plugin">
</form>```
Hmm...

**Comment by OctoNezd** [comment]
Looks like I found reason: Adding Plugin string doesnt have end.

**Comment by OctoNezd** [comment]
Fixed
