### ISSUE TITLE
Implement dark theme

### ISSUE THREAD

**Issue by OctoNezd** [OctoNezd/NTRDB#22]
With https://github.com/OctoNezd/NTRDB/commit/b8f95c1fb2bf7b4e962d4b18727e318145569828 it were implemented, but it doesnt remember which theme user has choose.

**Comment by martinmontane** [comment]
try using js and writing a file with the config. So that is user side rather than serverside

**Comment by OctoNezd** [comment]
@martinmontane I tried version w/ cookies, but it ducks up when user log ins

**Comment by pehcc** [comment]
I can try do it
I need to send PR?

**Comment by OctoNezd** [comment]
Yea

**Comment by OctoNezd** [comment]
Added!
