### ISSUE TITLE
UI/Layout

### ISSUE THREAD

**Issue by adrifcastr** [OctoNezd/NTRDB#23]
maybe it would be more useful to have the plugins in "cards" to get a better overview like TitleDB++ does.
https://shameless-inc.github.io/

**Comment by OctoNezd** [comment]
I think that would be good to have some sort of switch between two modes

**Comment by OctoNezd** [comment]
![image](https://cloud.githubusercontent.com/assets/15308404/23319767/fe39f402-fae8-11e6-9406-3a87767e8b87.png)
Added
