### ISSUE TITLE
I can create account without password

### ISSUE THREAD

**Issue by kovirolik** [OctoNezd/NTRDB#26]
I can create account without password
**Steps to reproduce**
1. Open register page
2.  Put any e-mail into e-mail field
3. Open inspector and remove required from password field
4. Press register button
5. ???
6. Profit!

**Comment by OctoNezd** [comment]
@kovirolik I dont think that really a big problem. But I will fix it

**Comment by OctoNezd** [comment]
Check if bug works with latest commit.

**Comment by kovirolik** [comment]
Still works

**Comment by OctoNezd** [comment]
Have you updated your local version or you are trying on mine site?

**Comment by kovirolik** [comment]
I'm bother tried to pull updates from repo and tried on your site

**Comment by OctoNezd** [comment]
Try again. Now it should dont allow you

**Comment by kovirolik** [comment]
thank you! Now this bug isn't working!

**Comment by OctoNezd** [comment]
Fixed with https://github.com/OctoNezd/NTRDB/commit/8e32df5f741830e4e6c4d1888ae27aab7922636c
