### ISSUE TITLE
Multiple TitleID not working properly

### ISSUE THREAD

**Issue by adrifcastr** [OctoNezd/NTRDB#29]
tryed to add Pokémon Moons Title id to pokeCalcNTR but it just gives a  "You entered bad TitleID!" , doesn´t matter how I place the semicolon with space or without.

**Comment by OctoNezd** [comment]
Can you try again? I think it fixed with latest commit

**Comment by adrifcastr** [comment]
still not working ;/

**Comment by OctoNezd** [comment]
Ugh

**Comment by OctoNezd** [comment]
Temporary disabled validation for TIDs in edit()

**Comment by OctoNezd** [comment]
Now it should work
