### ISSUE TITLE
Some stuff

### ISSUE THREAD

**Issue by JixunMoe** [OctoNezd/NTRDB#31]
* Image lightbox? Like [this](http://lokeshdhakar.com/projects/lightbox2/) and [this](http://noelboss.github.io/featherlight/).
* Click on " Show description" will scroll to top. Consider `event.preventDefault();`?

**Comment by OctoNezd** [comment]
Click on "Show descriptioin" fixed with https://github.com/OctoNezd/NTRDB/commit/fdd9e973d5f56d034969e4a815b9c99f94cb916d

**Comment by OctoNezd** [comment]
Lightbox added
