### ISSUE TITLE
Logout page is quite destroyed

### ISSUE THREAD

**Issue by OctoNezd** [OctoNezd/NTRDB#34]
## Steps to reproduce

1. Log in

2. Log out

3. Profit

## Expected

Normal logout page

## Happens

![image](https://cloud.githubusercontent.com/assets/15308404/23577083/8ee18f0e-00c7-11e7-9da5-e2d3f0f81e45.png)

**Comment by OctoNezd** [comment]
Fixed with latest commit

**Comment by evgfilim1** [comment]
@OctoNezd Next time use reference to issue/PR in commit message. For example, "Fixed logout page (#34)"

**Comment by OctoNezd** [comment]
@evgfilim1 I used it most of time tbh, but forgot this time
