### ISSUE TITLE
addUser() adds str instead of list into user likes data

### ISSUE THREAD

**Issue by imaboy321** [OctoNezd/NTRDB#36]
File: main.py
Line: 837
Error: TypeError

**Comment by macktns** [comment]
Having the same problem, only happened after logging in.

**Comment by martinmontane** [comment]
i'll look into it

**Comment by martinmontane** [comment]
can you give me more info, i can't reproduce the error

**Comment by imaboy321** [comment]
After logging in, it tries to direct you to the index page but this error occurs instead.

**Comment by OctoNezd** [comment]
@imaboy321 Is markup failed?
Can you say you logon so I could investigate issue

**Comment by imaboy321** [comment]
So I just opened the page without being logged in. I just logged in with my account with the email steviecook210@gmail.com. I am currently sitting at the page with the error.

**Comment by OctoNezd** [comment]
Issue may be in two things:

- Welcome back message

- Likes

**Comment by OctoNezd** [comment]
Can you try logging in again? 

P.S. I cant reproduce bug

**Comment by OctoNezd** [comment]
Ok, looks like it probably issue with likes:
![image](https://cloud.githubusercontent.com/assets/15308404/23584982/676fd550-0182-11e7-8e63-5e7e3479a5db.png)

**Comment by macktns** [comment]
Same problem still. Some plugins show when I am logged out.

**Comment by OctoNezd** [comment]
I find bug, working on it right now

**Comment by OctoNezd** [comment]
And this fix actually broke some stuff. Damn.

**Comment by OctoNezd** [comment]
Applied temporary fix

**Comment by OctoNezd** [comment]
Now you can login, but likes doesnt work due to unknown bug
