### ISSUE TITLE
Space missing + blank line

### ISSUE THREAD

**Issue by adrifcastr** [OctoNezd/NTRDB#4]
In the decription part, there are missing spaces after the :  and under Description: is a blank line, this are just some very small bugs but, I thought that I should also mention small things. :) 
![hgj](https://cloud.githubusercontent.com/assets/22133246/23027118/a1688490-f463-11e6-812d-5014605039a8.png)

**Comment by OctoNezd** [comment]
Fixed with https://github.com/OctoNezd/NTRDB/commit/bd8093f54910add0a58b2f1b346ae7c7b393bcd2
