### ISSUE TITLE
CORS error when reaching API

### ISSUE THREAD

**Issue by ghost** [OctoNezd/NTRDB#41]
## Steps to reproduce
1)Try to reach API via AJAX
2) See what happened
## Expected
Beautiful page with list of plugins (in my case)
## Happens

`XMLHttpRequest cannot load https://ntrdb.octonezd.pw/api. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://fiddle.jshell.net' is therefore not allowed access.`

**Comment by OctoNezd** [comment]
Should be fixed now probably

**Comment by OctoNezd** [comment]
Issue is probably fixed, if there would be any problems, I will reopen it
