### ISSUE TITLE
Search function is not working

### ISSUE THREAD

**Issue by Jolty95** [OctoNezd/NTRDB#5]
Pressing Search button make the browser say the connection has been reset (translation Spanish to English :P)

Also, if suggestion are available, I'd like to help you translating to Spanish (I'm umbjolt in gbatemp if you want to send me a PM when this happen :) )

**Comment by OctoNezd** [comment]
Fixed with https://github.com/OctoNezd/NTRDB/commit/b29c1ebf1f0e2908cf70ccfacbc16e49ac3f57a6
