### ISSUE TITLE
"Region Support"

### ISSUE THREAD

**Issue by adrifcastr** [OctoNezd/NTRDB#8]
like beeing able to add multiple title ids corresponding to the other regions.
I think that feature would also make it easier for somone who codes a downloader for it

(and don´t hurry take your time :) I´m just suggesting stuff /reporting bugs, you have all the time you want for doing anything you want)

**Comment by adrifcastr** [comment]
@OctoNezd this should be your next thing, cause we need it , else like CTGC7 would have 6 entries for example

**Comment by OctoNezd** [comment]
Yea, I think user will separate TIDs by `;`

**Comment by OctoNezd** [comment]
Also, this will change API quite a bit, so prepare yourself!

**Comment by adrifcastr** [comment]
Alright.

**Comment by OctoNezd** [comment]
![image](https://cloud.githubusercontent.com/assets/15308404/23332889/6ed9fc12-fb92-11e6-9545-926c892d993d.png)
Need to change some little things

**Comment by OctoNezd** [comment]
Added with https://github.com/OctoNezd/NTRDB/commit/85c5941248aae636ece18727e83314c3b512a9d9

**Comment by mostm** [comment]
@OctoNezd naxuy
